fix(server-steps): update usage of http-status-codes
form8ion/hapi-scaffolder pull request #238
Opened 2020-09-09 04:27 UTC by trevtrich

- this is the [newly recommended approach](https://github.com/prettymuchbryce/http-status-codes/releases/tag/v2.0.0)

2020-09-09 04:38 UTC, travi requested changes
lets switch this commit type to `refactor` instead of `fix` since there shouldnt be a behavior change to consumers

2020-09-11 03:30 UTC, trevtrich commented
@travi is this alright to merge now? (updated commit type)

2020-09-11 03:36 UTC, travi commented
Yep, sorry if I missed the update before

2020-09-11 03:37 UTC, travi approved these changes

2020-09-11 03:37 UTC, merged